public enum Operation
{    
    ADDITION,
    SUBTRACTION,
    SCALAR_MULTIPLICATION,
    MATRIX_MULTIPLICATION,
    TRANSPOSE,
    EQALITY_CHECK,
    TRANSLATION,
    SCALING,    
    ROTATION_2D,
    ROTATION_3D,
    WORLD_SPACE_TRANSFORMATION    
}