public enum Operation
{    
    ADDITION,
    SUBTRACTION,
    SCALAR_MULTIPLICATION,
    MATRIX_MULTIPLICATION,
    TRANSPOSE,
    EQALITY_CHECK,
    TRANSLATION,
    SCALING,
    ROTATION,
    WORLD_SPACE_TRANSFORMATION    
}